name: Continuous Integration

on:
  push:
    branches:
      - '*'  # Triggers the action on any branch push
  pull_request:
    branches:
      - '*'  # Triggers the action on pull request to any branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the build on Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out the repository

      - name: Set up Java JDK 11
        uses: actions/setup-java@v1  # Setup JDK 11 for Gradle
        with:
          java-version: '11'

      - name: Run Jenkinsfile Runner
        uses: jenkinsci/jenkinsfile-runner-action@v2  # Jenkinsfile Runner GitHub Action
        with:
          jenkinsfile: 'Jenkinsfile'  # Path to your Jenkinsfile
          jenkins_url: 'https://jenkins.io'  # Jenkins URL (can be local or cloud)
          docker_image: 'jenkins/jenkinsfile-runner'  # Docker image for Jenkinsfile Runner
